spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_db2
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  error:
    include-stacktrace: never

logging:
  level:
    org.springframework.security: trace